### ISSUE TITLE
Configure CI environment

### ISSUE THREAD

**Issue by JarJak** [bolt/four#113]
Configure CI to check every PR.
To be used (probably):
Travis
PhpUnit
PhpSpec
Behat
EasyCodingStandard
PhpStan

**Comment by bobdenotter** [comment]
Let's not forget: `eslint` or `prettier` for Javascript, Vue, Twig, and (S)CSS files.

**Comment by Ichag** [comment]
JS part one:
https://github.com/bolt/four/pull/127
Linting follows

**Comment by JarJak** [comment]
ECS:
#142
