### ISSUE TITLE
Update README to list commands in `Makefile`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#147]
We have a new `Makefile` by @JarJak . The README should be updated to reflect the updated commands.

**Comment by JarJak** [comment]
Due to problems with `make` command on Windows that @nestordedios spotted I'm not sure if we should that this OS-specific file to readme

**Comment by bobdenotter** [comment]
Right, then maybe we could describe it as such? "If you're on macos/linux, run `make foo`, otherwise run `x; y; z;`"
