### ISSUE TITLE
Create Content API endpoints for Frontend

### ISSUE THREAD

**Issue by JarJak** [bolt/four#150]
GET single and GET multiple, with sorting, search etc.
Can be tricky due to new Content - Field (EAV?) relation.
Hydra annotations should be added too.

**Comment by bobdenotter** [comment]
Is this different from what we already have listed in `/api`? If so, and it's considered useful to have, i'd be in favor of adding it.. 

I believe @jackiboy also had an opinion on GraphQL and/or Hydra. Let's discuss on how to proceed with this. :-)

**Comment by bobdenotter** [comment]
Added it to the Zenhub board: https://app.zenhub.com/workspaces/four-5befffc74b5806bc2bf587e7/boards?repos=135177880

**Comment by JarJak** [comment]
@bobdenotter jest it is different: in frontend we need only GET endpoints (+ POST in boltforms extension) and /fields endpoint doesn't make sense IMO, /content should return data the same way setcontent does (actually setcontent could use API Models internally), so:
- contents with fields with data
- paging
- searching
- returnsingle
- relations (bidirectional too)
etc.

**Comment by bobdenotter** [comment]
I know @nestordedios already did some work on this.. We can use the API to fetch Records, _with_ all its Fields.. @nestordedios, maybe you can chime in?

Futhermore, we might need `POST` (or `PUT`) endpoints for Fields. The main edit interface will be traditional server-request-response type interaction, but Jack made a start on the interface for "quick edit", so there it'd make sense if you could update a specific field like "title" or "status".

> Another thing is that IMO if we do headless AND traditional frontend, all API endpoints should be prefixed with /api 

Sure.. Perhaps even `/bolt/api/`?

**Comment by nestordedios** [comment]
@JarJak I'm not very familiar with API Platform yet and there are indeed points to improve.

>2. /fields endpoint doesn't make sense IMO

The reason I added the `Fields` entity to the Model is because the `Content` Entity has a collection of `Fields` Entities, and by not adding them to the Model the fields where not fetched in `api/contents/{id}` How to get that endpoint working without exposing `api/fields` in the API I haven't managed.
