### ISSUE TITLE
⭐️ Make `composer create-project` installable

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#166]

**Comment by JarJak** [comment]
To be included: way to enable/disable debug mode (with web profiler). Maybe with Symfony Recipe?

**Comment by bobdenotter** [comment]
Not yet finished at all, but it's kinda working: https://github.com/bolt/four-project

**Comment by bobdenotter** [comment]
Closing this for now.. Basic functionality is working. Extra goodies like toggling on/off the debug/profiler will be added later.
