### ISSUE TITLE
Errors when running `doctrine:fixtures:load`

### ISSUE THREAD

**Issue by xiaohutai** [bolt/four#169]
```
> bin/console doctrine:fixtures:load -n
```

```
  > purging database
  > loading Bolt\DataFixtures\UserFixtures
  > loading Bolt\DataFixtures\TaxonomyFixtures
  > loading Bolt\DataFixtures\ContentFixtures

In ReferenceRepository.php line 141:

  Reference to: () does not exist
```

![image](https://user-images.githubusercontent.com/4630335/49071805-1422a680-f22f-11e8-88f7-befc2846e6d5.png)

**Comment by bobdenotter** [comment]
Fixed in #170 and #171

**Comment by bobdenotter** [comment]
Oh, wait, this is a different issue.. Re-opening.

**Comment by xiaohutai** [comment]
Yeah, I removed the npm build part as it was fixed 👍 . Actually should've been two separate issues.
