### ISSUE TITLE
Make render more readable

### ISSUE THREAD

**Issue by stryxx** [bolt/four#213]
The most of all I found the problem with render function in Controller extends BackendBase.

If you want to have some specific variable's name, you have to define it in $globals array. It is wrong way. Global variables have to be in the "context" array like context.content as example. Local variables should be without context prefix.

```
render(string $templateName, array $locals = [], array $globals = [])
```

### **Actual result:**
In controller:
```
return $this->render('template.twig', [], ['test' => 'this is a test']);
```
In template.twig:
`{{ dump(test) }}`
Result:
```
'this is a test'
```

In controller:
```
return $this->render('template.twig', ['test' => 'this is a test']);
```
In template.twig:
`{{ dump(context.test) }}`
Result:
```
'this is a test'
```

In controller:
```
return $this->render('template.twig', ['test' => 'This is a test'], ['test2' => 'this is a test']);
```
In template.twig:
`{{ dump(test2) }}`
`{{ dump(context) }}`
`{{ dump(context.test) }}`
Result:
```
'this a test'
```

```
[
    (...),
    'test' => 'This is a test'
]
```
```
'This is a test'
```

### **Expected result:**
In controller:
```
return $this->render('template.twig', [], ['test' => 'this is a test']);
```
In template.twig:
`{{ dump(context.test) }}`
Result:
```
'this is a test'
```

In controller:
```
return $this->render('template.twig', ['test' => 'this is a test']);
```
In template.twig:
`{{ dump(test) }}`
Result:
```
'this is a test'
```

In controller:
```
return $this->render('template.twig', ['test' => 'This is a test'], ['test2' => 'this is a test']);
```
In template.twig:
`{{ dump(test) }}`
`{{ dump(context) }}`
`{{ dump(context.test2) }}`
Result:
```
'This a test'
```

```
[
    (...),
    'test2' => 'this is a test'
]
```
```
'this is a test'
```

**Comment by bobdenotter** [comment]
We'll have to think about what we want to put in the "global" space in twig. From the template implementor's perspective, it's really friendly, if you can do `{{ record.foo }}` or other things without having to prefix them like `{{ context.record.foo }}`.

**Comment by stryxx** [comment]
I agree with this but record can be default local value.

**Comment by JarJak** [comment]
Can we get rid of `context` entirely? What is this for?

**Comment by bobdenotter** [comment]
In Bolt 3 we made a distinction between this, but I think we've already gotten rid of it. 

Currently, BaseController has: 

```
    protected function renderTemplate($template, array $parameters = [], ?Response $response = null): Response
    {
        …

        $content = $twig->render($template, $parameters);
```

Which uses `vendor/twig/twig/lib/Twig/Environment.php`:

``` 
    public function render($name, array $context = array())
    {
        return $this->loadTemplate($name)->render($context);
    }
```

So, no distinction between `locals` and `globals` is already gone, right? 

If I remember correctly, this confusion originated in the decision upstream to deprecate true globals in Twig. Thankfully, they became "undeprecated": https://twig.symfony.com/doc/2.x/advanced.html#globals

So, we should use these as is -> You pass into `render()` what are considered "local" variables,and there are also globals, like `app`, and we don't have to deal with stupid `context`.
