### ISSUE TITLE
Make admin area URL prefix configurable

### ISSUE THREAD

**Issue by JarJak** [bolt/four#245]
For now `/bolt` is hardcoded in `routes.yaml`, `security.yaml` and some Vue components.
Let's make it configurable eg. with env variable.

Splitted from #242

**Comment by JarJak** [comment]
Also, firewall settings in `security.yaml` needs to be improved.

**Comment by bobdenotter** [comment]
@JarJak What needs to be done here? Would be good to be able to tick this one off as well.

**Comment by JarJak** [comment]
@bobdenotter what is not clear for you in task description?

**Comment by bobdenotter** [comment]
"Improved" is a bit vague. ;-)

PR upcoming, with a suggestion. See #378
