### ISSUE TITLE
Frontend: Make "Show relations for a record" work

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#252]
Additional issue for #232 

Depends on #163

**Comment by JarJak** [comment]
Let's make it working bidirectionally by default

**Comment by JarJak** [comment]
Have in mind relations in preview mode

**Comment by bobdenotter** [comment]
And also make `RelationshipExtras`, analogous to `ContentExtras`

**Comment by JarJak** [comment]
IMO relations endpoints can be more custom than simple relation entities. It can be based on Relation Twig extension.
