### ISSUE TITLE
Frontend application code cleanup

### ISSUE THREAD

**Issue by marcingajda** [bolt/four#280]
Goal of this issue is to improve the frontend application code base in both JavaScript and CSS files. This issue includes:
- Review Eslint and prettier configurations to match widely used standards.
- Add Stylelint for checking SCSS files
- Fix linting violations
- Do some code cleanups like removing unnecessary comment and files
- Improve directories structure

**Comment by bobdenotter** [comment]
👍

**Comment by bobdenotter** [comment]
@marcingajda Maybe also look at #129 ? There's not much activity from the author, but maybe there's some bits and pieces you can use?

**Comment by marcingajda** [comment]
@bobdenotter Yes, as I responded in that issue earlier I will grab the travis configuration. Sorry that it's taking me so much time, I wanted to finish it this weekend but I get sick 🤒Anyway all parts are done except the travis configuration and I have a problem with stylelint which doesn't want to autofix violations. Probably I will finish it before the end of this week.

**Comment by JarJak** [comment]
Closed by #307
