### ISSUE TITLE
Setcontent bug `setcontent homepage = "homepage/1"`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#282]
If i do this, I get an error: 

```
    {% setcontent homepage = "homepage/1" %}
```
![screenshot 2019-01-21 at 19 48 06](https://user-images.githubusercontent.com/1833361/51493383-81793080-1db5-11e9-8ea0-7bb8572498b2.png)

**Comment by xiaohutai** [comment]
Fixed in #286
