### ISSUE TITLE
Rename MarkDown.vue to Markdown.vue

### ISSUE THREAD

**Issue by ucay** [bolt/four#30]
Got this error when running encore on linux.
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                 02:52:08

This relative module was not found:

* ../Components/Editor/Markdown.vue in ./assets/js/Views/editor.js
```

Because the existing file is `MarkDown.vue` instead of `Markdown.vue`
Rename it should fix the problem.

**Comment by bobdenotter** [comment]
@jackiboy This one was fixed already, right?

**Comment by jackiboy** [comment]
@bobdenotter yup I have fixed this.

**Comment by ucay** [comment]
Reopen this issue.

![screenshot from 2018-10-29 08-05-17](https://user-images.githubusercontent.com/3348846/47624749-4c609780-db52-11e8-8c90-5affae2bfce1.png)
![screenshot from 2018-10-29 08-06-28](https://user-images.githubusercontent.com/3348846/47624750-4cf92e00-db52-11e8-89da-eb831cdae18d.png)

**Comment by bobdenotter** [comment]
That's super weird.. I would've sworn we fixed this.. Will do so again. Thanks! :-)
