### ISSUE TITLE
Unexpected "media" and other keys in Image field value

### ISSUE THREAD

**Issue by JarJak** [bolt/four#318]
Summary:
---
Saving `Image` field adds some extra fields, like "media" or "title". I don't know where they came from.

Steps to reproduce:
---
Through admin panel, save record with `image` field filled.
Then call `dump(record.image)`

Expected result:
---
```
{
  "filename": "kitten.jpg",
  "alt": "A cute kitten",
  "path": "/thumbs/kitten.jpg?w=240&h=160&area=files"
}
```

Actual result:
---
```
{
  "media": "",
  "filename": "kitten.jpg",
  "alt": "A cute kitten",
  "title": "",
   "0": "",
  "path": "/thumbs/kitten.jpg?w=240&h=160&area=files"
}
```

**Comment by bobdenotter** [comment]
Closing old issue.. Will be fixed (for now) in the upcoming changes to image.
