### ISSUE TITLE
Remove usages of collect()

### ISSUE THREAD

**Issue by JarJak** [bolt/four#333]
Because they will conflict if someone would use Bolt and Laravel in same project. It creates errors like
>  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Return value of Bolt\Configuration\Parser\BaseParser::parseConfigYaml() must be an instance of Tightenco\Collect\Support\Collection, instance of Illuminate\Support\Collection returned

**Comment by bobdenotter** [comment]
I get this error now too, and I wonder why, all of a sudden. 🤔
