### ISSUE TITLE
Twig breaks on `is defined`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#343]
This should work: 

```twig
    {% if record.foo is defined %}
        It should be defined if we get here
        {{ dump(record.foo) }}
    {% endif %}
```

Instead I get this error: 

![screenshot 2019-03-02 at 15 15 20](https://user-images.githubusercontent.com/1833361/53683182-1ac52c00-3cfe-11e9-8900-2795f31b6d42.png)

**Comment by JarJak** [comment]
Have you tried using http://php.net/manual/en/language.oop5.overloading.php#object.isset instead?
