### ISSUE TITLE
Think about better check on existence of nullable fields

### ISSUE THREAD

**Issue by JarJak** [bolt/four#349]
This task is the continuation of #344 .

We need to find a solution to distinguish `field that do not exist` from `field that exists but has value of null`.
`{% if record.title is defined %}` does not work by design.
`{% if record.title|default %}` does not work for now (throws an exception).

Possible solutions:
1. `{% if record.title %}` - title field exists and has value != null (0, empty string, empty array, false, etc.)
2. `{% if record.hasField('title') %}` or `{% record.title is set %}` - title field exists, don't care about it's value
3. `{% if record.title|default %}` - this does work on Bolt 3, we can check if same mechanism would work on Bolt 4

Also about throwing exceptions:
`{{ record.notExistingField }}` should not throw an exception, but
`{{ record.notExistingMethod() }}` should throw

TODO:
- check how it's done in Bolt 3

**Comment by bobdenotter** [comment]
> `{% if record.title %}`

Personally, I like this best. It just _looks_ more elegant than the other solutions, even though i'm fully aware it might not be the most explicit. 

> `{% if record.hasField('title') %}`

We already have this, and we should keep it for sure, for those cases when we need to be explicit. 

> `{% record.title is set %} `

Also looks pretty, but the way Twig works this means this can only work if `record.foo` works

> `{% if record.title|default %}` 

I like this least, but it _will_ work automatically if we allow option 1.

> {{ record.notExistingField }} should not throw an exception, but {{ record.notExistingMethod() }} should throw

Agreed 💯 

> check how it's done in Bolt 3

Bolt 3 has 2 types of content: `\Bolt\Legacy\Content` and `Bolt\Storage\Entity\Content`. Both implement `ArrayAccess`, which makes `record.foo` return `false` (_not_ `null`) in Twig.

**Comment by JarJak** [comment]
>{{ record.notExistingField }} should not throw an exception, but {{ record.notExistingMethod() }} should throw

Now I think this is something that can't be done because of how Twig works with `__call()`.
