### ISSUE TITLE
Missing attributes in `records|json_records`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#407]
After the introduction of #400, a few things are not displayed correctly in the backend. Namely this: 

![Schermafbeelding 2019-04-19 om 18 00 05](https://user-images.githubusercontent.com/1833361/56432268-013b6c00-62cd-11e9-895b-cf1d2669a35c.png)
![Schermafbeelding 2019-04-19 om 18 00 16](https://user-images.githubusercontent.com/1833361/56432270-03052f80-62cd-11e9-8835-fe5fa3dd73ae.png)

The Vue component that breaks is `assets/js/app/listing/Components/Table/Row/_Meta.vue`. 

Especially these values: 

`{{ record.author.displayName }}` -> can be replaced by `{{ record.authorName }}`

These two should be added: 

 - `{{ record.icon }}` -> which is coming from the `icon_one` from the contenttype definition
 - `{{ record.status }}` -> Which is the current status of the record.

**Comment by JarJak** [comment]
Are there some values of record that are not used in backend zone?

**Comment by bobdenotter** [comment]
I think they _all_ are, at some time.. Some like `depublishedAt` is not shown _yet_, but it will be in the contextual menu on the overview pages. So I think it should match what was in the old one at https://github.com/bolt/four/pull/400/files#diff-af5de60a97e3b51d356ac8b4647b2c95L54

**Comment by bobdenotter** [comment]
addition: `author/id` and `author/email` are _not_ needed.

**Comment by JarJak** [comment]
Can this one wait for Symfony Forms? Because a lot of things about Vue components will need to follow up there and things will break.
