### ISSUE TITLE
Make 'setcontent'

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#41]

**Comment by JarJak** [comment]
I hope it's implementation will be less magical than in v3 ;)

**Comment by bobdenotter** [comment]
@JarJak See #116 

It's being worked on by @xiaohutai.. It's definitely based on our Bolt 3 code, but converted to use ORM. I assume by "magic" you mostly mean the hydration, right? That should be handled by ORM now, and it seems much snappier than before.

**Comment by JarJak** [comment]
With "magical" I mean using user_func_*, side effects, implicit changing object state etc.

**Comment by bobdenotter** [comment]
Closed by #116
