### ISSUE TITLE
Determine what happens on very wide screens

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#473]
Should the "center" column stay together, or should they be spread out evenly? Is the currently chosen maximum width of editable content a good value?

**Comment by sbonardt** [comment]
In #510 and #474 I've made layout changes and set the containing element for the content editing screens to a max width. On very wide screens (around 1800px) the containing div is bound by the max width and the sidebar/aside nudges back in width one column to keep layout consistent and in line with smaller fields.
