### ISSUE TITLE
On a page with "widecontent" aside overlaps usable space

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#510]
See screenshot: 

![Screenshot 2019-07-08 at 21 28 41](https://user-images.githubusercontent.com/1833361/60837017-77ae8280-a1c7-11e9-9db6-462916b0e4d4.png)

**Comment by sbonardt** [comment]
I can fix this but I need some more info on the approach of the content. Currently the aside is written out although there is no content in it. I'm planning on running a check on the aside block if it has content set in the subtemplate. This way we can still define the HTML for the aside in the main template and not give others 'control' over the structure, which would happen if we move the HTML for the aside to the sub templates. I'll rework the styling for this as well

**Comment by bobdenotter** [comment]
Fixed in #521
