### ISSUE TITLE
Config editor for main config breaks layout

### ISSUE THREAD

**Issue by sbonardt** [bolt/four#522]
It seems when editing the config.yml through the UI in the backend, the config editor form/textarea is way too wide. Looks like some inline styles from a CodeMirror thingy.

The same form for the taxonomy editor looks nice so it looks like this is only something for the config.yml editor screen

**Comment by sbonardt** [comment]
![Screenshot 2019-07-10 at 14 34 25](https://user-images.githubusercontent.com/5597447/60969477-e6065880-a31f-11e9-9213-5425742d4140.png)
![Screenshot 2019-07-10 at 14 33 57](https://user-images.githubusercontent.com/5597447/60969478-e6065880-a31f-11e9-8b26-a69febf24df3.png)

**Comment by bobdenotter** [comment]
> The same form for the taxonomy editor looks nice so it looks like this is only something for the config.yml editor screen

`config.yml` has a very long line, that stretched the container. By putting a `width: 100%;` on the surrounding div, it's fixed.
