### ISSUE TITLE
Convert Twig-based "slug" field into Vue component. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#8]
Currently, the "slug" field is generated in HTML. Code for the field is here: https://github.com/bobdenotter/symfony-skeleton/blob/master/templates/editcontent/fields/slug.twig

<img width="867" alt="screenshot 2018-10-02 at 19 38 08" src="https://user-images.githubusercontent.com/1833361/46367310-79b64480-c67d-11e8-863a-148b6b2ebf4a.png">

Ideally, this field should be converted to a nice, self-contained Vue component, that's easier to maintain. 

Current JS code entry point is here: https://github.com/bobdenotter/symfony-skeleton/blob/master/assets/js/bolt.js

Build instructions are in README.md. After setting up, you should be able to log on to the Admin Panel, at `/bolt`, and from the Dashboard click on "Edit" on any of the dummy records to go to the Edit page. 

Note: the current code is very prototype-y. Feel free to re-arrange stuff, if it makes more sense. :-)

**Comment by jackiboy** [comment]
@bobdenotter you can close this badboy

**Comment by bobdenotter** [comment]
Fixed in #26
